

const greeting = guest => `Hello, ${guest}!`;
describe('greeting()', () => {
    it('says hello', () => {
        expect(greeting('Jest')).toBe('Hello, Jest!');
    }        
    );
});
//describe() declares a test suite, which is a grouping of tests. Its first argument is a name, and the second is a function containing one or more tests.
//it() declares a test. Its first argument is a name, and the second is a function with the actual test code.
//expect() creates an assertion. It takes a single argument, typically a value generated by the code being tested, and returns an object that exposes a set of matcher functions.
//toBe() is a matcher that performs a strict equality test between the value being tested (the expect() argument) and the expected value (its own argument).